//#undef MBEDTLS_PSA_INJECT_ENTROPY
#undef MBEDTLS_THREADING_C
#undef MBEDTLS_NET_C
#undef MBEDTLS_FS_IO
#undef MBEDTLS_PSA_ITS_FILE_C
#undef MBEDTLS_PSA_CRYPTO_STORAGE_C

#define MBEDTLS_PSA_CRYPTO_EXTERNAL_RNG
#define MBEDTLS_NO_PLATFORM_ENTROPY